# Generated by Django 5.2.4 on 2025-11-16 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0008_alter_buildinginformation_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vahanele_motori', models.BooleanField(default=False)),
                ('hazine_pezezhki', models.BooleanField(default=False)),
                ('jange_az_sanavi', models.BooleanField(default=False)),
                ('tabareh_66', models.BooleanField(default=False)),
                ('masouliat_ashkhas_sevom', models.BooleanField(default=False)),
                ('tedad_diyat', models.BooleanField(default=False)),
                ('mamooriat_khارج', models.BooleanField(default=False)),
                ('masouliat_mojri', models.BooleanField(default=False)),
                ('gharamat_roozane', models.BooleanField(default=False)),
                ('hazine_kargoshay', models.BooleanField(default=False)),
                ('tabareh_66_person', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tabareh_66_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mamooriat_khارج_person', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mamooriat_khارج_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gharamat_roozane_person', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gharamat_roozane_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hazine_kargoshay_person', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hazine_kargoshay_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('die_increase', models.BooleanField(default=False)),
                ('die_increase_option', models.CharField(blank=True, choices=[('1', 'حداکثر یکسال'), ('2', 'حداکثر دو سال'), ('3', 'حداکثر سه سال')], max_length=1, null=True)),
                ('signup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coverage', to='forms.signup')),
            ],
        ),
    ]
