# Generated by Django 5.2.4 on 2025-11-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverage',
            old_name='mamooriat_khارج',
            new_name='mamooriat_kharej',
        ),
        migrations.RenameField(
            model_name='coverage',
            old_name='mamooriat_khارج_person',
            new_name='mamooriat_kharej_person',
        ),
        migrations.RenameField(
            model_name='coverage',
            old_name='mamooriat_khارج_total',
            new_name='mamooriat_kharej_total',
        ),
    ]
