# Generated by Django 5.2.4 on 2025-12-31 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0002_rename_mamooriat_khارج_coverage_mamooriat_kharej_and_more'),
        ('forms', '0008_alter_buildinginformation_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'در حال تکمیل'), ('active', 'فعال'), ('issued', 'صادر شده')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coverage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Insurance.coverage')),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.signup')),
            ],
        ),
    ]
