# Generated by Django 5.2.5 on 2026-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0003_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='status',
            field=models.CharField(choices=[('draft', 'در انتظار پرداخت'), ('broke', 'پرداخت ناموفق'), ('active', 'منتظر دریافت نرخ'), ('issued', 'صادر شده')], default='draft', max_length=10),
        ),
    ]
