# Generated by Django 5.2.5 on 2026-02-10 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0004_alter_insurance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='policy_image',
            field=models.ImageField(blank=True, null=True, upload_to='insurance_policies/', verbose_name='عکس بیمه\u200cنامه'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='premium_quote',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='quote_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='coverage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Insurance.coverage'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='status',
            field=models.CharField(choices=[('quote_requested', 'درخواست نرخ'), ('quote_received', 'نرخ دریافت شد'), ('payment_pending', 'منتظر پرداخت'), ('payment_completed', 'پرداخت شد'), ('issued', 'صادر شده'), ('draft', 'پیش\u200cنویس'), ('failed', 'ناموفق')], default='draft', max_length=50),
        ),
    ]
