# Generated by Django 5.2.5 on 2026-09-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0005_insurance_payment_date_insurance_policy_image_and_more'),
        ('forms', '0008_alter_buildinginformation_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='forms.signup'),
        ),
    ]
