# Generated by Django 5.2.5 on 2026-09-08 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0006_alter_coverage_signup'),
        ('forms', '0008_alter_buildinginformation_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='mosque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='forms.mainregistration', verbose_name='مسجد'),
        ),
    ]
