# Generated by Django 5.2.5 on 2026-09-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0007_coverage_mosque'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
