# Generated by Django 5.2.4 on 2025-08-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='نام کاربری')),
                ('pasword', models.IntegerField(verbose_name='رمز عبور')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
            ],
        ),
    ]
