# Generated by Django 5.2.4 on 2025-08-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='pasword',
        ),
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default='', max_length=30, verbose_name='رمز عبور'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='نام کاربری'),
        ),
    ]
