# Generated by Django 5.2.4 on 2025-10-05 13:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_signup_pasword_signup_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mosque_name', models.CharField(max_length=50, verbose_name='نام مسجد')),
                ('mosque_id', models.IntegerField(verbose_name='کد شناسایی مسجد')),
                ('mosque_Capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='ظرفیت نمازگزار')),
                ('mosque_postalcode', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000)], verbose_name='کدپستی مسجد')),
                ('mosque_address', models.CharField(max_length=200, verbose_name='آدرس مسجد')),
                ('mosque_phone', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(90000000000)], verbose_name='تلفن ثابت مسجد')),
                ('created_phone', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(9000000000)], verbose_name='تلفن موبایل')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ثبت نام اصلی',
            },
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=200, verbose_name='رمز عبور'),
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servan_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد خادمین')),
                ('fullname_servan', models.CharField(max_length=30, verbose_name='نام و نام خانوادگی')),
                ('person_role', models.CharField(max_length=60, verbose_name='نقش فرد')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='forms.mainregistration', verbose_name='ثبت نام اصلی')),
            ],
            options={
                'verbose_name': 'لیست خادمین',
            },
        ),
    ]
