# Generated by Django 5.2.4 on 2025-10-07 12:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_mainregistration_alter_signup_password_personinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainregistration',
            options={'verbose_name': 'لیست مساجد'},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'کاربران'},
        ),
        migrations.AddField(
            model_name='mainregistration',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mosque', to='forms.signup', verbose_name='اطلاعات پایه'),
        ),
        migrations.AlterField(
            model_name='mainregistration',
            name='mosque_phone',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تلفن ثابت مسجد'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='forms.mainregistration', verbose_name='خادمین'),
        ),
        migrations.CreateModel(
            name='BuildingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_land_area', models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(10000)], verbose_name='متراژ کل زمین')),
                ('total_bulding_area', models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(10000)], verbose_name='متراژ زیربنا')),
                ('user_type', models.CharField(max_length=25, verbose_name='نوع کاربری')),
                ('structure_type', models.CharField(max_length=25, verbose_name='نوع سازه')),
                ('structure_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='قدمت')),
                ('structure_meterage', models.IntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(10000)])),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='forms.mainregistration', verbose_name='بنا')),
            ],
            options={
                'verbose_name': 'اطلاعات ساختمان',
            },
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimeHavades', models.BooleanField(default=False, verbose_name='بیمه حوادث؟')),
                ('dakhelRahn', models.BooleanField(default=False, verbose_name='رهن ساختمان در داخل؟')),
                ('dakhelVagozar', models.BooleanField(default=False, verbose_name='واگذاری ساختمان در داخل؟')),
                ('kharejMalek', models.BooleanField(default=False, verbose_name='مالک فضای خارج از مسجد؟')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='forms.mainregistration', verbose_name='سوالات')),
            ],
            options={
                'verbose_name': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='TrusteesBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_TrusteesBoard', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name=' هیات امنا')),
                ('boss_fullname', models.CharField(verbose_name='نام و نام خانوادگی رئیس هیات امنا')),
                ('boss_nationalcode', models.CharField(max_length=10, verbose_name='کد ملی رئیس هیات امنا')),
                ('boss_phone', models.CharField(max_length=11, verbose_name='تلفن همراه رئیس هیات امنا')),
                ('boss_birthday', models.DateField(verbose_name='تاریخ تولد رئیس هیات امنا')),
                ('secretary_fullname', models.CharField(verbose_name='نام و نام خانوادگی دبیر هیاامنا')),
                ('secretary_nationalcode', models.CharField(max_length=10, verbose_name='کد ملی دبیر هیات امنا')),
                ('secretary_phone', models.CharField(max_length=11, verbose_name='تل همراه دبیر هیات امنا')),
                ('secretary_birthday', models.DateField(verbose_name='تاریخ تولد دبیر هیات امنا')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrusteesBoard', to='forms.mainregistration')),
            ],
            options={
                'verbose_name': 'هیات امنا',
            },
        ),
    ]
