# Generated by Django 5.2.4 on 2025-10-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_mainregistration_options_alter_signup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainregistration',
            name='registration',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='mosque', to='forms.signup', verbose_name='اطلاعات پایه'),
            preserve_default=False,
        ),
    ]
