# Generated by Django 5.2.4 on 2025-10-11 11:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_mainregistration_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainregistration',
            name='created_phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='تلفن موبایل'),
        ),
        migrations.AlterField(
            model_name='mainregistration',
            name='mosque_phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='تلفن ثابت مسجد'),
        ),
        migrations.AlterField(
            model_name='mainregistration',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosque', to='forms.signup', verbose_name='کاربر ثبت کننده'),
        ),
    ]
