# Generated by Django 5.2.4 on 2025-10-11 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_mainregistration_created_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainregistration',
            name='mosque_postalcode',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='کدپستی مسجد'),
        ),
    ]
