# Generated by Django 5.2.4 on 2025-11-11 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_mainregistration_mosque_postalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinginformation',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='forms.mainregistration', verbose_name='بنا'),
        ),
    ]
