# Generated by Django 5.2.4 on 2025-12-31 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Insurance', '0003_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شد'), ('failed', 'ناموفق')], default='pending', max_length=20)),
                ('authority', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Insurance.coverage')),
            ],
        ),
    ]
