# Generated by Django 5.2.5 on 2026-02-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='coverage',
        ),
    ]
