# Generated by Django 5.2.5 on 2026-02-10 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0005_insurance_payment_date_insurance_policy_image_and_more'),
        ('payment', '0002_remove_payment_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='insurance_data',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Insurance.insurance'),
            preserve_default=False,
        ),
    ]
